name: Remover
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  TEST:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Remove
        env:
          S_VARIABLE: ${{ vars.S_VARIABLE }}
        run: |
          export S_VARIABLE
          sed -i "s/<li>$S_VARIABLE<\/li>/<li class=\"done\"><s>$S_VARIABLE<\/s><\/li>/g" index.html

      - name: Commit and push
        run: |
          echo ""
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git add index.html

          if ! git diff --staged --quiet; then
            git commit -m "Update index.html"
            git push
          fi
